const mongoose = require('mongoose');

const PropertySchema = new mongoose.Schema({
  owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, required: true },
  description: { type: String, required: true },
  location: { type: String, required: true },
  rentAmount: { type: Number, required: true },
  propertyType: { type: String, required: true }, // e.g. Apartment, House, Room, etc.
  furnishingStatus: { type: String, enum: ['Furnished', 'Semi-Furnished', 'Unfurnished'], default: 'Unfurnished' },
  amenities: [{ type: String }],
  images: [{ type: String }],
  status: { type: String, enum: ['Available', 'Booked', 'Draft', 'Pending', 'Under Review', 'Approved', 'Rejected', 'Published', 'Rented', 'Sold', 'Archived', 'Expired', 'Live', 'Active'], default: 'Draft' },
  securityDeposit: { type: Number, default: 0 },
  maintenance: { type: Number, default: 0 },
  bedrooms: { type: Number, default: 2 },
  bathrooms: { type: Number, default: 2 },
  balcony: { type: Number, default: 0 },
  floor: { type: Number, default: 0 },
  totalFloors: { type: Number, default: 1 },
  facing: { type: String, default: 'East' },
  area: { type: Number, default: 1000 },
  latitude: { type: Number, default: 19.0760 },
  longitude: { type: Number, default: 72.8777 },
  address: { type: String, default: '' },
  state: { type: String, default: '' },
  city: { type: String, default: '' },
  areaName: { type: String, default: '' },
  locality: { type: String, default: '' },
  street: { type: String, default: '' },
  landmark: { type: String, default: '' },
  pinCode: { type: String, default: '' },
  video: { type: String, default: '' },
  virtualTour: { type: String, default: '' },
  floorPlan: { type: String, default: '' },
  ownershipDoc: { type: String, default: '' },
  nearbySchools: [{ type: String }],
  nearbyHospitals: [{ type: String }],
  nearbyMetro: [{ type: String }],
  busStop: [{ type: String }],
  restaurants: [{ type: String }],
  shoppingMalls: [{ type: String }],
  parks: [{ type: String }],
  parking: { type: String, default: 'None' },
  furnishing: { type: String, default: 'Unfurnished' },
  propertyAge: { type: Number, default: 0 },
  tags: [{ type: String }],
  seoMetadata: {
    title: { type: String, default: '' },
    description: { type: String, default: '' },
    keywords: { type: String, default: '' }
  },
  googleMapUrl: { type: String, default: '' },
  streetViewUrl: { type: String, default: '' },
  scheduledPublishDate: { type: Date },
  expiryDate: { type: Date },
  isBoosted: { type: Boolean, default: false },
  isFeatured: { type: Boolean, default: false },
  isArchived: { type: Boolean, default: false },
  views: { type: Number, default: 0 },
  wishlistCount: { type: Number, default: 0 },
  rejectionReason: { type: String, default: '' },
  history: [{
    status: String,
    updatedAt: { type: Date, default: Date.now },
    notes: String
  }]
}, { timestamps: true });

module.exports = mongoose.model('Property', PropertySchema);

